name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile-go-1 --tag my-image-name:$(date +%s)
    - name: Docker Package Registry
      uses: craftech-io/package-action@v3.1.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Test the image
      run: docker run docker.pkg.github.com/devsecol/docker-intro/docker-intro:4125e5fcd677473db5d37bd62c4c4bfe500e6e2d ls
